
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ecolor = 14;
  public static final int eaccioni = 15;
  public static final int eventanaf = 18;
  public static final int eaccionf = 16;
  public static final int coma = 4;
  public static final int importa = 5;
  public static final int ietiqueta = 9;
  public static final int eventana = 8;
  public static final int num = 2;
  public static final int etipo = 12;
  public static final int direcc = 7;
  public static final int eid = 11;
  public static final int EOF = 0;
  public static final int funcionn = 17;
  public static final int fimporta = 6;
  public static final int error = 1;
  public static final int asigna = 13;
  public static final int fetiqueta = 10;
  public static final int txtcom = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "num",
  "txtcom",
  "coma",
  "importa",
  "fimporta",
  "direcc",
  "eventana",
  "ietiqueta",
  "fetiqueta",
  "eid",
  "etipo",
  "asigna",
  "ecolor",
  "eaccioni",
  "eaccionf",
  "funcionn",
  "eventanaf"
  };
}

