
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int fimporta = 6;
  public static final int num = 2;
  public static final int error = 1;
  public static final int direcc = 7;
  public static final int coma = 4;
  public static final int txtcom = 3;
  public static final int importa = 5;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "num",
  "txtcom",
  "coma",
  "importa",
  "fimporta",
  "direcc"
  };
}

